### ISSUE TITLE
USER STORY: LOVE Running

### ISSUE THREAD

**Issue by Lochy2000** [Lochy2000/love-running#1]
In order to **receive benefit** as a **role**, I can **goal / desire**

In order to **improve website interactions** as a **runner**, I can give my **input in a poll.**

In order to **widen the running community** as a **runner**, I can provide my feedback in a **comment section** on the landing page.

**Comment by Lochy2000** [comment]
In order to improve website interactions as a runner, I can give my input in a poll.

## Acceptance Criteria
- [ ] A drop down box check box
- [ ] User can pick one or more boxes
- [ ] User must pick at least one checkbox before submitting 

## Task 
- [ ]  Update the poll adding the relevant html and css to add a check box and dropdown 
- [ ] Update function
- [ ] Check boxes can be clicked
- [ ] check that form will not submit unless a box has been ticket
